name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: "Publish to npm"
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Verify tag is on main
        run: git merge-base --is-ancestor ${{ github.sha }} origin/main
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org"
      - run: corepack enable
      - run: yarn install
      - run: yarn build
      - run: npm publish --provenance --access public
